sudo: required
language: python

branches:
  only:
  - master

services:
  - docker

before_install:
- git submodule update --init el4000

script:
- version=$(git describe)
- docker build --build-arg APP_VERSION=$version -t $DOCKER_USERNAME/energy-logger-ui:$version .
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push $DOCKER_USERNAME/energy-logger-ui:$version
