sudo: required
language: python

services:
  - docker

before_install:
- git submodule update --init el4000

script:
- docker build -t $DOCKER_USERNAME/energy-logger-ui:$(git describe) .
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push $DOCKER_USERNAME/energy-logger-ui:$(git describe)
